name: heicy
base: core20
version: '1.0'
summary: HEIC photos to PNG converter
description: You can convert HEIC photos from your Apple iPhone to PNG
grade: stable
confinement: strict

parts:
  heicy:
    plugin: go
    source: .

apps:
  heicy:
    extensions: [gnome-3-38]
    command: bin/heicy
